### Getting from Devious

This command retrieves any set of the most recent versions of added files to Devious by the user or any collaborators. This includes most recent file changes stored in Devious and/or current file permissions and group specifications in the configuration file.

#### R Command

In R, this command may look like:

```{r}
dvs_get(files = c("path/to/file1", "path/to/file2"))
```

-   `files` is a vector of file glob characters representing the set of files to be copied back from the initialized storage directory to the directory in which its metadata file exists.

-   its output is a data frame whose rows are the added files and the columns for a given file are its:

    -   `path`: relative to the git directory
    -   `hash`: from blake3 (if successfully created)
    -   `outcome` of getting - one of the following:
        -   `Copied`
        -   `Error`
        -   `Already Present`
        -   `Permissions Updated`
        -   `Group Updated`
        -   `Group and Permissions Updated`
    -   `error` summary if the `outcome` was `Error`
    -   `size` in bytes

#### Shell Command

In Shell, this command may look like: (TODO: implement)

```         
dvs get path/to/file1 path/to/file2
```

-   the input is a space-separated of file globs representing the set of files to be copied back from the initialized storage_directory

#### Implementation Details:

-   `.gitignore` files and repeated files are skipped in the first argument to prevent unexpected behavior.

-   files ending in `.dvsmeta` are stripped of this extension to aid in parsing file globs and tab-completed fields.

#### Errors

If the project directory is not a git repository, or the configuration file cannot be found, the function returns an error.

If any errors pertaining to a specific file occur, a contextualizing message with each error is printed, but an error isn't returned.

In R's interface, the first occurring error is given in the `error` column of the returned data frame.

#### List of Potential Errors

-   path is a directory
-   metadata file not found
-   file not copied
