# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_Rdevious_wrappers", use_symbols = TRUE, package_name = "Rdevious")

#' @docType package
#' @usage NULL
#' @useDynLib Rdevious, .registration = TRUE
NULL

dvs_init_impl <- function(storage_dir, mode, group, strict) .Call(wrap__dvs_init_impl, storage_dir, mode, group, strict)

dvs_add_impl <- function(globs, message, strict) .Call(wrap__dvs_add_impl, globs, message, strict)

dvs_get_impl <- function(globs) .Call(wrap__dvs_get_impl, globs)

dvs_status_impl <- function(files) .Call(wrap__dvs_status_impl, files)


# nolint end
